name: Journey of a Thousand Places
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfdfff'
    - '#1b1b1b'
    - '#4d5756'
    - '#c98672'
    - '#aa121e'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
