name: Journey of a Thousand Places
favicon: null
layout_spectrum: 0.26715
typography_spectrum: 0.11233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfdfff'
    - '#1b1b1b'
    - '#4d5756'
    - '#c98672'
    - '#aa121e'
  brandStrength: 0.25
  lightness: 0.020780530758202076
  saturation: 0.1875
  rhythmicContrast: 0.3013665040489286
purpose: []
