name: Journey of a Thousand Places
favicon: null
layout_spectrum: 0.26715
typography_spectrum: 0.11233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaf5fb'
    - '#071226'
    - '#76b8ec'
    - '#346cd9'
    - '#1f315f'
  brandStrength: 0.7681701097171754
  lightness: 0.020780530758202076
  saturation: 0.644170377869159
  rhythmicContrast: 0.3013665040489286
purpose: []
