name: Journey of a Thousand Places
favicon: null
layout_spectrum: 0.36418
typography_spectrum: 0.10242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#fefdf8'
    - '#b3b1be'
    - '#676386'
    - '#f5d78f'
  brandStrength: 0.7681701097171754
  lightness: 0.020780530758202076
  saturation: 0.644170377869159
  rhythmicContrast: 0.3013665040489286
purpose: []
